atlas_name_iterables = ['aal','allen','basc','craddock','craddock','destrieux'] #,'difumo','harvard_oxford','juelich','msdl','pauli','pauli','smith','talairach','yeo']
atlas_params_iterables = [{},{},{},{},{},{}] #,{'dimension':128},{'atlas_name':'cort-maxprob-thr0-1mm',{'atlas_name':'maxprob-thr0-1mm'},{},{'version':'det'},{},{},{'level_name':'ba'},{}]
labelmap_params_iterables = [(),('rsn28',),('122',),('scorr_mean',19),('tcorr_mean',19),()] #,(),(),(),(),(),(),('rsn70',),(),('thick_17',)]
modules_name_iterables = ['basc']
modules_params_iterables = [{}]
modules_labelmap_params_iterables = [('7',)]
