def plot_roi(roi_img, bg_img=None, cut_coords=5, output_file=None, display_mode='mosaic', figure=None, axes=None,
             title=None, annotate=True, draw_cross=True, black_bg=True, threshold=0.5, alpha=0.7,
             cmap='tab10', dim='auto', vmin=None, vmax=None, resampling_interpolation='nearest', view_type='continuous',
             linewidths=2.5, colorbar=False, save_img=True, **kwargs):
    """

    Wrapper for nilearn's plot_roi method (with small modifications).

    Can be used in a nipype function node. In this case output_file should stay None and save_img should stay True!

    Parameters:
        Only parameter that does not occur in nilearn's plot_roi method is save_img.
        Set to False if you don't want to save the result and just need the plot object.
        This parameter is necessary because we substitute output_file by the current working directory and a suitable
        filename if output_file is set to None (default).
        In case the function is executed within a nipype function node, the current working directory is the working
        directory of the respective node.
        We introduced this modifications in order to be able to use this method easily in nipype function nodes.

    For more information about the other parameters, see the documentation of nilearn.
    https://nilearn.github.io/modules/generated/nilearn.plotting.plot_roi.html

    Only a few changes have been made to the default parameters.
    Here a mosaic plot with 5 columns is generated by default, the background of every plot is black and the default
    cmap has been changed.

    ATTENTION: If save_img is set to False, then you must close the plot yourself!
    Otherwise this could lead to memory leaks!

    Returns:
        plot (nilearn.plotting.displays.OrthoSlicer): Plot object.
        output_file (str): Path to the saved plot (if save_img is False, None is returned).

    Acknowledgements:
        Further informations:
            - https://nilearn.github.io/index.html

    """
    from nilearn import plotting
    import os

    if save_img:
        # User wants to save the image directly and doesn't want to only get the plot object to modify it further
        # before saving.
        if output_file is None:
            roi_img_name = roi_img.split('/')[-1].split('.')[0]  # Get filename without extension.
            # Plot will be saved in current working directory with the filename (without extension) of ROI image.
            # but with the suffix '_plot.png'
            output_file = os.path.join(os.getcwd(), roi_img_name + '_plot.png')
        else:
            # If the user has specified an absolute path, then we can directly use it.
            # If we have only received a relative path, then we append this relative path to the current working
            # directory.
            if not output_file.startswith('/'):
                output_file = os.path.join(os.getcwd(), output_file)
    else:
        output_file = None
        # If output_file is None, then nilearn won't save the image.
        # In this case, the user must close the plot themself! Otherwise this could lead to memory leaks!

    plot = plotting.plot_roi(roi_img, bg_img=bg_img, cut_coords=cut_coords, output_file=output_file,
                             display_mode=display_mode, figure=figure, axes=axes, title=title, annotate=annotate,
                             draw_cross=draw_cross,
                             black_bg=black_bg, threshold=threshold, alpha=alpha, cmap=cmap, dim=dim, vmin=vmin,
                             vmax=vmax, resampling_interpolation=resampling_interpolation, view_type=view_type,
                             linewidths=linewidths, colorbar=colorbar, **kwargs)

    return plot, output_file


def create_segmentation_qc(overlay, bg_img=None, output_file=None, cut_coords=5, cmap='winter', **kwargs):
    """

    Create segmentation (e.g. brain extraction, tissue segmentation) quality check images.

    Can be used in a nipype function node. In this case output_file should stay None!

    Parameters:
        overlay (str): Path to the overlay (e.g. in brain extraction workflows the extracted brain).
        bg_img (str): Path to the background (e.g. in brain extraction workflows the head).
        output_file (str): Filename of quality check image. Can be be an absolute path or a relative path.
                           If it's set to None (default), the filename is automatically generated.
        cmap (matplotlib colormap): Colormap.
        **kwargs: These parameters are passed to the plot_roi method.

    Returns:
        output_file (str): Path to the saved plot.

    """
    from PUMI.utils import plot_roi

    plot, output_file = plot_roi(roi_img=overlay, bg_img=bg_img, output_file=output_file, cut_coords=cut_coords,
                                 cmap=cmap, **kwargs)
    return output_file


def create_coregistration_qc(registered_brain, template, output_file=None, levels=None, cmap='winter', **kwargs):
    """

    Create coregistration quality check images.

    Can be used in a nipype function node. In this case output_file should stay None!

    Parameters
    ----------
    registered_brain (str): Path to the registered brain.
    template (str): Path to the used template (reference) file.
    output_file (str): Filename of quality check image. Can be be an absolute path or a relative path.
                       If it's set to None (default), the path and filename is automatically generated.
    levels (list): Contour fillings levels. If set to None, [0.5] will be used.
    cmap (matplotlib colormap): Colormap.
    **kwargs: These parameters are passed to plot_roi method.

    Returns
    ----------
    output_file (str): Path to the saved plot.

    """
    from PUMI.utils import plot_roi
    import os

    if levels is None:
        levels = [0.5]

    plot, _ = plot_roi(roi_img=registered_brain, bg_img=template, cmap=cmap, alpha=0, save_img=False, **kwargs)
    plot.add_contours(registered_brain, levels=levels, colors='r')

    if output_file is None:
        registered_brain_filename = registered_brain.split('/')[-1].split('.')[0]
        output_file = os.path.join(os.getcwd(), registered_brain_filename + '_plot.png')
    else:
        if not output_file.startswith('/'):
            output_file = os.path.join(os.getcwd(), output_file)

    plot.savefig(output_file)
    plot.close()

    return output_file
